export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const LOG_OUT = "LOG_OUT"
export const LOG_ADMIN_IN = "LOG_ADMIN_IN"
export const LOG_USER_IN = "LOG_USER_IN"
